// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AcceptFriend(arg1:string):Promise<{[key: string]: any}>;

export function AddFriend(arg1:string):Promise<{[key: string]: any}>;

export function AuthVerify():Promise<{[key: string]: any}>;

export function ChangeAvatar(arg1:string):Promise<{[key: string]: any}>;

export function ChangeBanner(arg1:Array<number>,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number,arg7:string):Promise<{[key: string]: any}>;

export function ChangeDPName(arg1:string):Promise<{[key: string]: any}>;

export function ChangeEmail(arg1:string):Promise<{[key: string]: any}>;

export function ChangeNameColor(arg1:string):Promise<{[key: string]: any}>;

export function ChangeUsername(arg1:string):Promise<{[key: string]: any}>;

export function CreateCategory(arg1:string):Promise<{[key: string]: any}>;

export function CreateChannel(arg1:string):Promise<{[key: string]: any}>;

export function CreateInvitation(arg1:string):Promise<{[key: string]: any}>;

export function CreateMessage(arg1:any,arg2:string,arg3:string,arg4:Array<string>,arg5:string,arg6:boolean,arg7:string,arg8:Array<main.File>):Promise<{[key: string]: any}>;

export function CreateServer(arg1:string):Promise<{[key: string]: any}>;

export function DeleteCategory(arg1:string):Promise<{[key: string]: any}>;

export function DeleteChannel(arg1:string):Promise<{[key: string]: any}>;

export function DeleteFriend(arg1:string):Promise<{[key: string]: any}>;

export function DeleteMessage(arg1:string):Promise<{[key: string]: any}>;

export function DeleteServer(arg1:string):Promise<{[key: string]: any}>;

export function EditMessage(arg1:string):Promise<{[key: string]: any}>;

export function GenerateRoomToken(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function GetFriends(arg1:string):Promise<{[key: string]: any}>;

export function GetMessages(arg1:string):Promise<{[key: string]: any}>;

export function GetNotifications(arg1:string):Promise<{[key: string]: any}>;

export function GetProfile(arg1:string):Promise<{[key: string]: any}>;

export function GetServer(arg1:string):Promise<{[key: string]: any}>;

export function GetServers(arg1:string):Promise<{[key: string]: any}>;

export function Greet(arg1:string):Promise<string>;

export function IndicateTyping(arg1:string):Promise<{[key: string]: any}>;

export function IsAuthenticated():Promise<{[key: string]: any}>;

export function JoinServer(arg1:string):Promise<{[key: string]: any}>;

export function LogoutHudori():Promise<{[key: string]: any}>;

export function QuitServer(arg1:string):Promise<{[key: string]: any}>;

export function RefuseFriend(arg1:string):Promise<{[key: string]: any}>;

export function SignIn(arg1:string):Promise<{[key: string]: any}>;

export function SyncNotifications(arg1:string):Promise<{[key: string]: any}>;
