// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFriend(arg1) {
  return window['go']['main']['App']['AcceptFriend'](arg1);
}

export function AddFriend(arg1) {
  return window['go']['main']['App']['AddFriend'](arg1);
}

export function AuthVerify() {
  return window['go']['main']['App']['AuthVerify']();
}

export function ChangeAvatar(arg1) {
  return window['go']['main']['App']['ChangeAvatar'](arg1);
}

export function ChangeBanner(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ChangeBanner'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ChangeDPName(arg1) {
  return window['go']['main']['App']['ChangeDPName'](arg1);
}

export function ChangeEmail(arg1) {
  return window['go']['main']['App']['ChangeEmail'](arg1);
}

export function ChangeNameColor(arg1) {
  return window['go']['main']['App']['ChangeNameColor'](arg1);
}

export function ChangeUsername(arg1) {
  return window['go']['main']['App']['ChangeUsername'](arg1);
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreateChannel(arg1) {
  return window['go']['main']['App']['CreateChannel'](arg1);
}

export function CreateInvitation(arg1) {
  return window['go']['main']['App']['CreateInvitation'](arg1);
}

export function CreateMessage(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateMessage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CreateServer(arg1) {
  return window['go']['main']['App']['CreateServer'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteChannel(arg1) {
  return window['go']['main']['App']['DeleteChannel'](arg1);
}

export function DeleteFriend(arg1) {
  return window['go']['main']['App']['DeleteFriend'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['main']['App']['DeleteMessage'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function EditMessage(arg1) {
  return window['go']['main']['App']['EditMessage'](arg1);
}

export function GenerateRoomToken(arg1, arg2) {
  return window['go']['main']['App']['GenerateRoomToken'](arg1, arg2);
}

export function GetFriends(arg1) {
  return window['go']['main']['App']['GetFriends'](arg1);
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetNotifications(arg1) {
  return window['go']['main']['App']['GetNotifications'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetServer(arg1) {
  return window['go']['main']['App']['GetServer'](arg1);
}

export function GetServers(arg1) {
  return window['go']['main']['App']['GetServers'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IndicateTyping(arg1) {
  return window['go']['main']['App']['IndicateTyping'](arg1);
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function JoinServer(arg1) {
  return window['go']['main']['App']['JoinServer'](arg1);
}

export function LogoutHudori() {
  return window['go']['main']['App']['LogoutHudori']();
}

export function QuitServer(arg1) {
  return window['go']['main']['App']['QuitServer'](arg1);
}

export function RefuseFriend(arg1) {
  return window['go']['main']['App']['RefuseFriend'](arg1);
}

export function SignIn(arg1) {
  return window['go']['main']['App']['SignIn'](arg1);
}

export function SyncNotifications(arg1) {
  return window['go']['main']['App']['SyncNotifications'](arg1);
}
